#! /bin/sh

bspc config top_padding		 30
bspc config border_width         1 
bspc config window_gap           25
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config click_to_focus	 true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc monitor -d 1 2 3 4 5 6 7 8

bspc rule -a Screenkey manage=off
bspc rule -a Kupfer.py focus=on

$HOME/.config/polybar/launch.sh &
compton --config /home/dan/.config/compton.conf &

sxhkd &


